### PR TITLE
Add the association 'Tagged' belongs to 'Tags'

### PR DESCRIPTION
**Pull request by Phillaf**
This association allows to use matching() like this

```
$articles = $this->Articles->find()
    ->matching('Tagged.Tags', function($q) {
        return $q->where(['Tags.label' => 'someLabel']);
    });
```

refs: #28

### CODE REVIEW

**Comment by ADmad** [comment]
@Phillaf Patch looks good but pgsql builds are failing after your last commit

**Comment by ADmad** [comment]
Sorry for making comments on the commits instead of this PR.

**Comment by Phillaf** [comment]
Current test fails on php 5.4 and 5.6. A simple version bump from cake 3.0 to 3.1 makes the test fail on php 5.5 only. Reordering fixtures makes tests fail on all three versions. Still haven't figured what's up.

**Comment by jadb** [comment]
@Phillaf - any updates on this?

**Comment by Phillaf** [comment]
I'm at loss here. I hoped someone knew the answer without me having to xdebug the ORM etc. I won't have much time for debugging in the next couple of weeks.

**Comment by jadb** [comment]
Hmm am not sure I was even following - @ADmad any ideas?

**Comment by ADmad** [comment]
@jadb I did have a look at it initially but couldn't figure how to fix the postgres error.

**Comment by dereuromark** [comment]
I implemented this in the new tags repo @ https://github.com/dereuromark/cakephp-tags

**Comment by burzum** [comment]
@dereuromark why aren't you fixing it in this repo or at least forking it but creating a new repo?

**Comment by dereuromark** [comment]
I like retorical questions :)

**Comment by burzum** [comment]
@dereuromark this was not a rhetoric question.

**Comment by dereuromark** [comment]
Take a look at the activity and it will be. Also helps to look at my attempts of PRs etc.

**Pull request closed without merging**
