### PR TITLE
Fixing a possible notice.

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by jadb** [comment]
Thanks :wink:

**Comment by ADmad** [comment]
Maybe my caffeine hasn't kicked in, what's the possible notice here?  `unset()` doesn't throw notice for non-existent keys.

**Comment by jadb** [comment]
Hmm - i guess I had not have enough caffeine when I reviewed it first [here](https://github.com/UseMuffin/Tags/issues/16).

**Comment by burzum** [comment]
I don't remember what caused it but this was the fix for me.

**Pull request merged**
